### ISSUE TITLE
Clarify what assumptions this package intends to protect

### ISSUE THREAD

**Issue by mdempsky** [go4org/unsafe-assume-no-moving-gc#3]
Strictly speaking, cmd/compile already has a moving GC: stacks can grow and shrink, and variables that are stack allocated may have their address visibly change during runtime: https://play.golang.org/p/t3VX4YVDYYT

**Comment by kke** [comment]
As seen in the go 1.20 formula update for homebrew, a huge number of projects fail to build as some of their dependencies has decided to import this package. This has delayed the go 1.20 availability on brew for everyone. I think this does more harm than good.

It seems this has been imported from several packages that just happen to use `unsafe` "just in case", I believe the problem this repo is trying to anticipate involves some very specific use of `unsafe` and the people who have imported this do not understand what this repo is trying to do either.

This @mdempsky 's question has gone unanswered for two years.

I would advise everyone to not depend on this package unless they very clearly and exactly understand what the problem is they're trying to solve by importing this.

**Comment by bradfitz** [comment]
It specifically is about moving GC of heap-allocated objects, not things on the stack.

This package was made specifically for go4.org/intern which was needed by inet.af/netaddr before it was in the standard library as `net/netip`. It gave us some peace of mind that if we got distracted and didn't finish that project/migration and left it in some intermediate state, we wouldn't be responsible for random memory corruption in somebody's project 5 years down the road. It was better for lack of effort on our part to cause a build breakage than corruption.

Any package depending on this is package is suspect and probably playing stupid games. I think the cost of having to `go get @upgrade` this package occasionally is useful for keeping an eye on those suspect packages.
